# Generated by Django 5.2.1 on 2025-07-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoices_sales',
        ),
    ]
