# Generated by Django 5.2.1 on 2025-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0002_delete_invoices_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_vencimiento', models.TextField(null=True)),
                ('codigo_cliente', models.TextField(null=True)),
                ('cliente', models.TextField(null=True)),
                ('org_comercial', models.TextField(null=True)),
                ('agente', models.TextField(null=True)),
                ('documento', models.TextField(null=True)),
                ('transaccion', models.TextField(null=True)),
                ('importe', models.FloatField(null=True)),
                ('importe_cobrado', models.FloatField(null=True)),
                ('fecha_factura', models.TextField(null=True)),
                ('fecha_vencimiento', models.TextField(null=True)),
                ('fecha_cobro', models.TextField(null=True)),
                ('status_cobro', models.TextField(null=True)),
                ('dias_real_pago', models.FloatField(null=True)),
                ('dias_exceso', models.FloatField(null=True)),
            ],
        ),
    ]
