# Generated by Django 5.2.1 on 2025-07-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessales',
            name='ejercicio',
            field=models.TextField(null=True),
        ),
    ]
