# Generated by Django 5.2.1 on 2025-07-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_invoicessales_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessales',
            name='dag',
            field=models.TextField(null=True),
        ),
    ]
