# Generated by Django 5.2.1 on 2025-07-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_invoicessales_dag'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessales',
            name='updated',
            field=models.TextField(null=True),
        ),
    ]
