# Generated by Django 5.2.1 on 2025-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_invoicessales_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessales',
            name='info_error',
            field=models.TextField(null=True),
        ),
    ]
