# Generated by Django 5.2.1 on 2025-07-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_invoicessales_info_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicessales',
            old_name='info_error',
            new_name='forma_cobro',
        ),
    ]
