# Generated by Django 5.2.1 on 2025-07-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_rename_info_error_invoicessales_forma_cobro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicessales',
            name='transaccion',
        ),
    ]
