# Generated by Django 5.2.1 on 2025-07-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_remove_invoicessales_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessales',
            name='status_vencimiento',
            field=models.TextField(null=True),
        ),
    ]
