# Generated by Django 5.2.1 on 2025-07-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_invoicessales_status_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicessales',
            name='estado_vencimiento',
        ),
    ]
