# Generated by Django 5.2.1 on 2025-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_remove_invoicessales_estado_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicessales',
            name='documento',
            field=models.TextField(null=True, unique=True),
        ),
    ]
