# Generated by Django 5.2.1 on 2025-08-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Powerbireports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.TextField(null=True)),
                ('user_name', models.TextField(null=True)),
                ('report_link', models.TextField(null=True)),
            ],
        ),
    ]
