# Generated by Django 5.2.1 on 2025-08-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powerbireports',
            old_name='user_name',
            new_name='user_names',
        ),
    ]
