# Generated by Django 5.2.1 on 2025-10-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(null=True)),
                ('sent', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('file', models.TextField(null=True)),
                ('time_log', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('role', models.TextField(null=True)),
                ('permissions', models.TextField(null=True)),
                ('first_visit', models.TextField(null=True)),
                ('last_visit', models.TextField(null=True)),
                ('num_visit', models.BigIntegerField(null=True)),
                ('ip', models.TextField(null=True)),
                ('action_pass', models.TextField(null=True)),
            ],
        ),
    ]
