# Generated by Django 5.2.1 on 2025-10-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_code',
            field=models.TextField(null=True),
        ),
    ]
