# Generated by Django 5.2.1 on 2025-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_users_email_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
