# Generated by Django 5.2.1 on 2025-10-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='permissions',
            new_name='department',
        ),
    ]
