# Generated by Django 5.2.1 on 2025-10-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_permissions_users_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='permissions',
            field=models.TextField(null=True),
        ),
    ]
