# Generated by Django 5.2.1 on 2025-10-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_users_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='action_pass',
        ),
    ]
