# Generated by Django 5.2.1 on 2025-10-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_users_action_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='action_pass',
            field=models.TextField(null=True),
        ),
    ]
