# Generated by Django 5.2.1 on 2025-10-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_users_action_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='department',
            new_name='department_id',
        ),
        migrations.AddField(
            model_name='users',
            name='department_name',
            field=models.TextField(null=True),
        ),
    ]
