# Generated by Django 5.2.1 on 2025-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_department_users_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='department_id',
            field=models.IntegerField(null=True),
        ),
    ]
