# Generated by Django 5.2.1 on 2025-10-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_users_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='department_name',
        ),
    ]
