# Generated by Django 5.2.1 on 2025-10-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_users_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='department_name',
            field=models.TextField(null=True),
        ),
    ]
