# Generated by Django 5.2.1 on 2025-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCostsHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(max_length=22, unique=True)),
                ('article_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCostsLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_article', models.CharField(max_length=22)),
                ('article_code', models.CharField(max_length=22)),
                ('article_name', models.TextField(null=True)),
                ('percentage', models.IntegerField(null=True)),
                ('alternative', models.TextField(null=True)),
            ],
        ),
    ]
