# Generated by Django 5.2.1 on 2025-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecostshead',
            name='created_at',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='articlecostshead',
            name='updated_at',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
