# Generated by Django 5.2.1 on 2025-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_articlecostshead_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecostslines',
            name='article_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlecostslines',
            name='parent_article',
            field=models.IntegerField(null=True),
        ),
    ]
