# Generated by Django 5.2.1 on 2025-05-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_articlecostslines_article_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecostshead',
            name='article_code',
            field=models.IntegerField(unique=True),
        ),
    ]
