# Generated by Django 5.2.1 on 2025-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_articlecostshead_article_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecostslines',
            name='percentage',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
