# Generated by Django 5.2.1 on 2025-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_alter_articlecostslines_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecostslines',
            name='percentage',
            field=models.DecimalField(decimal_places=1, max_digits=11, null=True),
        ),
    ]
