# Generated by Django 5.2.1 on 2025-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_alter_articlecostslines_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCostsPriceMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp', models.IntegerField(null=True)),
                ('name', models.TextField(null=True)),
                ('date_top', models.TextField(null=True)),
                ('current_cost', models.FloatField(null=True)),
                ('month_end_cost', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articlecostslines',
            name='percentage',
            field=models.FloatField(null=True),
        ),
    ]
