# Generated by Django 5.2.1 on 2025-05-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_articlecostspricemonth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecostspricemonth',
            old_name='date_top',
            new_name='cost_date',
        ),
        migrations.RemoveField(
            model_name='articlecostspricemonth',
            name='current_cost',
        ),
        migrations.RemoveField(
            model_name='articlecostspricemonth',
            name='month_end_cost',
        ),
    ]
