# Generated by Django 5.2.1 on 2025-05-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_rename_date_top_articlecostspricemonth_cost_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCostsPriceMonth',
        ),
    ]
