# Generated by Django 5.2.1 on 2025-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_delete_articlecostspricemonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecostshead',
            name='cost_date',
            field=models.TextField(null=True),
        ),
    ]
