# Generated by Django 5.2.1 on 2025-05-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_articlecostshead_cost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelAdditionalCalculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp', models.IntegerField(null=True)),
                ('name', models.TextField(null=True)),
            ],
        ),
    ]
