# Generated by Django 5.2.1 on 2025-06-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_exceladditionalcalculations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelCalculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp', models.IntegerField(null=True)),
                ('name', models.TextField(null=True)),
                ('coste_actual_seco_kg', models.FloatField(null=True)),
                ('coste_seco_fin_kg', models.FloatField(null=True)),
                ('rendimiento', models.FloatField(null=True)),
                ('precio_materia_prima', models.FloatField(null=True)),
                ('precio_aceite', models.FloatField(null=True)),
                ('precio_servicios', models.FloatField(null=True)),
                ('aditivos', models.FloatField(null=True)),
                ('mod', models.FloatField(null=True)),
                ('embalajes', models.FloatField(null=True)),
                ('amort_maq', models.FloatField(null=True)),
                ('moi', models.FloatField(null=True)),
                ('coste_menos2', models.FloatField(null=True)),
                ('coste_menos1', models.FloatField(null=True)),
                ('coste_actual', models.FloatField(null=True)),
                ('coste_mas1', models.FloatField(null=True)),
                ('coste_mas2', models.FloatField(null=True)),
                ('coste_mas3', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExcelAdditionalCalculations',
        ),
    ]
