# Generated by Django 5.2.1 on 2025-06-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0013_delete_excelcalculations_articlecostshead_aditivos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelLinesEditable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.IntegerField(unique=True)),
                ('article_name', models.TextField(null=True)),
                ('rendimiento', models.FloatField(null=True)),
                ('precio_materia_prima', models.FloatField(null=True)),
                ('precio_aceite', models.FloatField(null=True)),
                ('precio_servicios', models.FloatField(null=True)),
                ('aditivos', models.FloatField(null=True)),
                ('mod', models.FloatField(null=True)),
                ('embalajes', models.FloatField(null=True)),
                ('amort_maq', models.FloatField(null=True)),
                ('moi', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articlecostshead',
            name='aditivos',
        ),
        migrations.RemoveField(
            model_name='articlecostshead',
            name='amort_maq',
        ),
        migrations.RemoveField(
            model_name='articlecostshead',
            name='embalajes',
        ),
        migrations.RemoveField(
            model_name='articlecostshead',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='articlecostshead',
            name='moi',
        ),
        migrations.RemoveField(
            model_name='articlecostshead',
            name='precio_aceite',
        ),
        migrations.RemoveField(
            model_name='articlecostshead',
            name='precio_materia_prima',
        ),
        migrations.RemoveField(
            model_name='articlecostshead',
            name='precio_servicios',
        ),
        migrations.RemoveField(
            model_name='articlecostshead',
            name='rendimiento',
        ),
    ]
