# Generated by Django 5.2.1 on 2025-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_excellineseditable_remove_articlecostshead_aditivos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellineseditable',
            name='original_coste_act',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='excellineseditable',
            name='original_coste_mas1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='excellineseditable',
            name='original_coste_mas2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='excellineseditable',
            name='original_coste_mas3',
            field=models.FloatField(null=True),
        ),
    ]
