# Generated by Django 5.2.1 on 2025-06-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0015_excellineseditable_original_coste_act_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excellineseditable',
            old_name='original_coste_act',
            new_name='final_coste_act',
        ),
        migrations.RenameField(
            model_name='excellineseditable',
            old_name='original_coste_mas1',
            new_name='final_coste_mas1',
        ),
        migrations.RenameField(
            model_name='excellineseditable',
            old_name='original_coste_mas2',
            new_name='final_coste_mas2',
        ),
        migrations.RenameField(
            model_name='excellineseditable',
            old_name='original_coste_mas3',
            new_name='final_coste_mas3',
        ),
    ]
