# Generated by Django 5.2.1 on 2025-06-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0016_rename_original_coste_act_excellineseditable_final_coste_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellineseditable',
            name='inicio_coste_act',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='excellineseditable',
            name='inicio_coste_mas1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='excellineseditable',
            name='inicio_coste_mas2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='excellineseditable',
            name='inicio_coste_mas3',
            field=models.FloatField(null=True),
        ),
    ]
