# Generated by Django 5.2.1 on 2025-06-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0017_excellineseditable_inicio_coste_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellineseditable',
            name='precio_padre_act',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='excellineseditable',
            name='precio_padre_fm',
            field=models.FloatField(null=True),
        ),
    ]
