# Generated by Django 5.2.1 on 2025-06-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0018_excellineseditable_precio_padre_act_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excellineseditable',
            name='precio_padre_fm',
        ),
    ]
