# Generated by Django 5.2.1 on 2025-06-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0019_remove_excellineseditable_precio_padre_fm'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalentsHeades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.TextField(unique=True)),
                ('alternative', models.TextField(null=True)),
            ],
        ),
    ]
