# Generated by Django 5.2.1 on 2025-06-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0020_equivalentsheades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquivalentsHeades',
            new_name='EquivalentsHead',
        ),
    ]
