# Generated by Django 5.2.1 on 2025-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0022_excellineseditable_precio_padre_mas_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalentshead',
            name='kg0',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='kg1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='kg2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='kg3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='price0',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='price1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='price2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='price3',
            field=models.FloatField(null=True),
        ),
    ]
