# Generated by Django 5.2.1 on 2025-06-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0023_equivalentshead_kg0_equivalentshead_kg1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalentshead',
            name='kg_act',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='price_act',
            field=models.FloatField(null=True),
        ),
    ]
