# Generated by Django 5.2.1 on 2025-06-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0024_equivalentshead_kg_act_equivalentshead_price_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEntradasEquivCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('entrada', models.TextField(unique=True)),
                ('stock_actual', models.FloatField(null=True)),
                ('pcm_actual', models.FloatField(null=True)),
                ('consumo', models.FloatField(null=True)),
                ('entrada_kg', models.FloatField(null=True)),
                ('entrada_eur', models.FloatField(null=True)),
                ('calc_kg', models.FloatField(null=True)),
                ('calc_eur', models.FloatField(null=True)),
            ],
        ),
    ]
