# Generated by Django 5.2.1 on 2025-06-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0025_detalleentradasequivcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentradasequivcc',
            name='updated_at',
            field=models.TextField(null=True),
        ),
    ]
