# Generated by Django 5.2.1 on 2025-06-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0026_detalleentradasequivcc_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleentradasequivcc',
            old_name='consumo',
            new_name='consumo_prod',
        ),
        migrations.AddField(
            model_name='detalleentradasequivcc',
            name='consumo_vent',
            field=models.FloatField(null=True),
        ),
    ]
