# Generated by Django 5.2.1 on 2025-06-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0027_rename_consumo_detalleentradasequivcc_consumo_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleentradasequivcc',
            name='entrada',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detalleentradasequivcc',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
