# Generated by Django 5.2.1 on 2025-06-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0028_alter_detalleentradasequivcc_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleentradasequivcc',
            name='updated_at',
        ),
    ]
