# Generated by Django 5.2.1 on 2025-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0029_remove_detalleentradasequivcc_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbarketIndividualRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.TextField(unique=True)),
                ('article_code', models.TextField(null=True)),
                ('kg_act', models.FloatField(null=True)),
                ('price_act', models.FloatField(null=True)),
                ('kg0', models.FloatField(null=True)),
                ('price0', models.FloatField(null=True)),
                ('kg1', models.FloatField(null=True)),
                ('price1', models.FloatField(null=True)),
                ('kg2', models.FloatField(null=True)),
                ('price2', models.FloatField(null=True)),
                ('kg3', models.FloatField(null=True)),
                ('price3', models.FloatField(null=True)),
                ('kg4', models.FloatField(null=True)),
                ('price4', models.FloatField(null=True)),
                ('kg5', models.FloatField(null=True)),
                ('price5', models.FloatField(null=True)),
                ('kg6', models.FloatField(null=True)),
                ('price6', models.FloatField(null=True)),
                ('kg7', models.FloatField(null=True)),
                ('price7', models.FloatField(null=True)),
                ('kg8', models.FloatField(null=True)),
                ('price8', models.FloatField(null=True)),
                ('kg9', models.FloatField(null=True)),
                ('price9', models.FloatField(null=True)),
                ('kg10', models.FloatField(null=True)),
                ('price10', models.FloatField(null=True)),
            ],
        ),
    ]
