# Generated by Django 5.2.1 on 2025-06-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0030_embarketindividualrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmbarketIndividualRating',
            new_name='EmbarkedIndividualRating',
        ),
    ]
