# Generated by Django 5.2.1 on 2025-06-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0031_rename_embarketindividualrating_embarkedindividualrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmbarkedIndividualRating',
            new_name='EmbarkedIndividualRatingDetail',
        ),
    ]
