# Generated by Django 5.2.1 on 2025-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0033_rename_kg0_embarkedindividualratingdetail_calc_eur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbarkedIndividualRatingHorizontal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('code', models.TextField(null=True)),
                ('mercado', models.TextField(null=True)),
                ('fecha', models.TextField(null=True)),
                ('stock', models.FloatField(null=True)),
                ('precio', models.FloatField(null=True)),
            ],
        ),
    ]
