# Generated by Django 5.2.1 on 2025-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0034_embarkedindividualratinghorizontal'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarkedindividualratingdetail',
            name='mercado',
            field=models.TextField(null=True),
        ),
    ]
