# Generated by Django 5.2.1 on 2025-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0035_embarkedindividualratingdetail_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarkedindividualratingdetail',
            name='familia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='embarkedindividualratingdetail',
            name='subfamilia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='embarkedindividualratinghorizontal',
            name='familia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='embarkedindividualratinghorizontal',
            name='subfamilia',
            field=models.TextField(null=True),
        ),
    ]
