# Generated by Django 5.2.1 on 2025-08-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0036_embarkedindividualratingdetail_familia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellineseditable',
            name='precio_standar',
            field=models.FloatField(null=True),
        ),
    ]
