# Generated by Django 5.2.1 on 2025-08-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0037_excellineseditable_precio_standar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excellineseditable',
            old_name='precio_standar',
            new_name='precio_estandar',
        ),
    ]
