# Generated by Django 5.2.1 on 2025-08-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0038_rename_precio_standar_excellineseditable_precio_estandar'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalentshead',
            name='precio_estandar_equival',
            field=models.FloatField(null=True),
        ),
    ]
