# Generated by Django 5.2.1 on 2025-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0039_equivalentshead_precio_estandar_equival'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionCostsVPBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.TextField(null=True)),
                ('fecha', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('title', models.FloatField(null=True)),
            ],
        ),
    ]
