# Generated by Django 5.2.1 on 2025-08-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0040_projectioncostsvpbi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectioncostsvpbi',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
