# Generated by Django 5.2.1 on 2025-08-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0041_alter_projectioncostsvpbi_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalentItemsVPBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.TextField(null=True)),
                ('fecha', models.TextField(null=True)),
                ('kg_act', models.FloatField(null=True)),
                ('price_act', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
