# Generated by Django 5.2.1 on 2025-08-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0042_equivalentitemsvpbi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalentitemsvpbi',
            name='price_act',
            field=models.TextField(null=True),
        ),
    ]
