# Generated by Django 5.2.1 on 2025-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0043_alter_equivalentitemsvpbi_price_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalentitemsvpbi',
            name='price_act',
            field=models.FloatField(null=True),
        ),
    ]
