# Generated by Django 5.2.1 on 2025-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0044_alter_equivalentitemsvpbi_price_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellineseditable',
            name='precio_estandar_con_gastos',
            field=models.FloatField(null=True),
        ),
    ]
