# Generated by Django 5.2.1 on 2025-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0045_excellineseditable_precio_estandar_con_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalentshead',
            name='kg4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='kg5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='kg6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='kg7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='price4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='price5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='price6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='equivalentshead',
            name='price7',
            field=models.FloatField(null=True),
        ),
    ]
