# Generated by Django 5.2.1 on 2025-09-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0046_equivalentshead_kg4_equivalentshead_kg5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equivalentshead',
            name='kg7',
        ),
        migrations.RemoveField(
            model_name='equivalentshead',
            name='price7',
        ),
    ]
