# Generated by Django 5.2.1 on 2025-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOrdersInTheLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.IntegerField(null=True)),
                ('track_id', models.IntegerField(null=True)),
                ('order_id', models.TextField(null=True)),
                ('article_id', models.TextField(null=True)),
            ],
        ),
    ]
