# Generated by Django 5.2.1 on 2025-08-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listordersintheload',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
