# Generated by Django 5.2.1 on 2025-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_listordersintheload_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listordersintheload',
            name='load_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='listordersintheload',
            name='track_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
