# Generated by Django 5.2.1 on 2025-08-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_alter_listordersintheload_load_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelsClicked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.IntegerField(db_index=True, null=True)),
                ('track_id', models.IntegerField(db_index=True, null=True)),
                ('number_all_order', models.IntegerField(null=True)),
                ('number_clicked_order', models.IntegerField(null=True)),
            ],
        ),
    ]
