# Generated by Django 5.2.1 on 2025-08-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_travelsclicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelsclicked',
            name='palets',
            field=models.FloatField(null=True),
        ),
    ]
