# Generated by Django 5.2.1 on 2025-08-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_travelsclicked_palets'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderListBelinLoads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.IntegerField(db_index=True, null=True)),
                ('load_date', models.TextField(null=True)),
                ('track_id', models.IntegerField(db_index=True, null=True)),
                ('track_name', models.TextField(null=True)),
                ('article_code', models.TextField(null=True)),
                ('article_name', models.TextField(null=True)),
                ('clicked', models.IntegerField(null=True)),
                ('palets', models.FloatField(null=True)),
            ],
        ),
    ]
