# Generated by Django 5.2.1 on 2025-08-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_orderlistbelinloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlistbelinloads',
            name='order_id',
            field=models.TextField(null=True),
        ),
    ]
