# Generated by Django 5.2.1 on 2025-08-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_orderlistbelinloads_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlistbelinloads',
            old_name='article_code',
            new_name='articles',
        ),
        migrations.RemoveField(
            model_name='orderlistbelinloads',
            name='article_name',
        ),
    ]
