# Generated by Django 5.2.1 on 2025-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_rename_article_code_orderlistbelinloads_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlistbelinloads',
            name='client_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderlistbelinloads',
            name='cliente_name',
            field=models.TextField(null=True),
        ),
    ]
