# Generated by Django 5.2.1 on 2025-08-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_orderlistbelinloads_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlistbelinloads',
            name='orden',
            field=models.IntegerField(null=True),
        ),
    ]
