# Generated by Django 5.2.1 on 2025-08-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_orderlistbelinloads_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlistbelinloads',
            name='input_palets',
            field=models.FloatField(null=True),
        ),
    ]
