# Generated by Django 5.2.1 on 2025-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_orderlistbelinloads_input_palets'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlistbelinloads',
            name='load_week',
            field=models.TextField(null=True),
        ),
    ]
