# Generated by Django 5.2.1 on 2025-08-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_orderlistbelinloads_load_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlistbelinloads',
            old_name='track_id',
            new_name='truck_id',
        ),
        migrations.RenameField(
            model_name='orderlistbelinloads',
            old_name='track_name',
            new_name='truck_name',
        ),
    ]
