# Generated by Django 5.2.1 on 2025-08-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0013_rename_track_id_orderlistbelinloads_truck_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlistbelinloads',
            old_name='cliente_name',
            new_name='client_name',
        ),
    ]
