# Generated by Django 5.2.1 on 2025-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0014_rename_cliente_name_orderlistbelinloads_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlistbelinloads',
            name='alb_id',
            field=models.TextField(null=True),
        ),
    ]
