# Generated by Django 5.2.1 on 2025-08-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0015_orderlistbelinloads_alb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlistbelinloads',
            old_name='alb_id',
            new_name='delivery_note_id',
        ),
    ]
