# Generated by Django 5.2.1 on 2025-08-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0016_rename_alb_id_orderlistbelinloads_delivery_note_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlistbelinloads',
            name='delivery_note_id',
        ),
    ]
