# Generated by Django 5.2.1 on 2025-08-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0017_remove_orderlistbelinloads_delivery_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlistbelinloads',
            name='click_info',
            field=models.TextField(null=True),
        ),
    ]
