# Generated by Django 5.2.1 on 2025-08-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0018_orderlistbelinloads_click_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListOrdersInTheLoad',
        ),
        migrations.DeleteModel(
            name='TravelsClicked',
        ),
    ]
