# Generated by Django 5.2.1 on 2025-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0019_delete_listordersintheload_delete_travelsclicked'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderArtcilesRegionalLoads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.IntegerField(db_index=True, null=True)),
                ('load_date', models.TextField(null=True)),
                ('article_code', models.TextField(null=True)),
                ('article_name', models.TextField(null=True)),
            ],
        ),
    ]
