# Generated by Django 5.2.1 on 2025-09-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0020_orderartcilesregionalloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='cajas_ped',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='codigo_familia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='conductor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='ejercicio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='exportado',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='fecha_carga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='matricula',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='pedido',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='preparado',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='und_ped',
            field=models.TextField(null=True),
        ),
    ]
