# Generated by Django 5.2.1 on 2025-09-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0021_orderartcilesregionalloads_cajas_ped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderartcilesregionalloads',
            name='load_id',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
