# Generated by Django 5.2.1 on 2025-09-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0022_alter_orderartcilesregionalloads_load_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderartcilesregionalloads',
            name='exportado',
        ),
        migrations.RemoveField(
            model_name='orderartcilesregionalloads',
            name='fecha_carga',
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='clicked',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderartcilesregionalloads',
            name='article_code',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderartcilesregionalloads',
            name='ejercicio',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
