# Generated by Django 5.2.1 on 2025-09-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0023_remove_orderartcilesregionalloads_exportado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderartcilesregionalloads',
            name='load_date',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
