# Generated by Django 5.2.1 on 2025-09-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0024_alter_orderartcilesregionalloads_load_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='cajas_real',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='kg_real',
            field=models.FloatField(null=True),
        ),
    ]
