# Generated by Django 5.2.1 on 2025-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0025_orderartcilesregionalloads_cajas_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='desglose',
            field=models.TextField(null=True),
        ),
    ]
