# Generated by Django 5.2.1 on 2025-09-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0026_orderartcilesregionalloads_desglose'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderartcilesregionalloads',
            name='desglose_ticado',
            field=models.TextField(null=True),
        ),
    ]
