# Generated by Django 5.2.1 on 2025-10-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_Tags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_id', models.BigIntegerField(null=True)),
                ('tag_id', models.BigIntegerField(null=True)),
                ('tag_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('descrption', models.TextField(null=True)),
                ('user_id', models.BigIntegerField(null=True)),
                ('user_name', models.TextField(null=True)),
                ('created_at', models.TextField(null=True)),
                ('updated_at', models.TextField(null=True)),
                ('department_id', models.TextField(null=True)),
                ('expiration_date', models.TextField(null=True)),
                ('notification_emails', models.TextField(null=True)),
                ('file_name', models.TextField(null=True)),
                ('file_path', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('user_id', models.BigIntegerField(null=True)),
                ('user_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users_Departments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(null=True)),
                ('user_name', models.TextField(null=True)),
                ('department_id', models.BigIntegerField(null=True)),
                ('department_name', models.TextField(null=True)),
            ],
        ),
    ]
