# Generated by Django 5.2.1 on 2025-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_tags',
            name='document_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document_tags',
            name='tag_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='department_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users_departments',
            name='department_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users_departments',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
