# Generated by Django 5.2.1 on 2025-10-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0002_alter_document_tags_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='department_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='department_name',
            field=models.TextField(null=True),
        ),
    ]
