# Generated by Django 5.2.1 on 2025-10-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0003_tag_department_id_tag_department_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='department_name',
        ),
    ]
