# Generated by Django 5.2.1 on 2025-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0004_delete_departments_remove_documents_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='department_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='department_name',
            field=models.TextField(null=True),
        ),
    ]
