# Generated by Django 5.2.1 on 2025-10-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0005_documents_department_id_documents_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='department_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='department_name',
            field=models.TextField(null=True),
        ),
    ]
