# Generated by Django 5.2.1 on 2025-10-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0006_tag_department_id_tag_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='file_size_mb',
            field=models.FloatField(null=True),
        ),
    ]
