# Generated by Django 5.2.1 on 2025-10-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0007_documents_file_size_mb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsLines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_id', models.BigIntegerField(db_index=True, null=True)),
                ('file_name', models.TextField(null=True)),
                ('file_path', models.TextField(null=True)),
                ('file_size_mb', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='file_size_mb',
        ),
        migrations.AlterField(
            model_name='document_tags',
            name='document_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document_tags',
            name='tag_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='department_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='user_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='department_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='users_departments',
            name='department_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='users_departments',
            name='user_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
