# Generated by Django 5.2.1 on 2025-10-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0008_documentslines_remove_documents_file_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentsLines',
            new_name='Documents_Lines',
        ),
    ]
