# Generated by Django 5.2.1 on 2025-10-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0009_rename_documentslines_documents_lines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
