# Generated by Django 5.2.1 on 2025-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentor', '0010_rename_tag_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents_lines',
            name='department_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='documents_lines',
            name='user_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
