# Generated by Django 5.2.1 on 2025-06-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froxa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfroxa',
            name='ip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userfroxa',
            name='last_visit',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userfroxa',
            name='num_visit',
            field=models.BigIntegerField(null=True),
        ),
    ]
