# Generated by Django 5.2.1 on 2025-06-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froxa', '0002_userfroxa_ip_userfroxa_last_visit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfroxa',
            old_name='lastvisit',
            new_name='first_visit',
        ),
        migrations.RemoveField(
            model_name='userfroxa',
            name='numvisit',
        ),
    ]
