# Generated by Django 5.2.1 on 2025-06-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froxa', '0003_rename_lastvisit_userfroxa_first_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfroxa',
            name='action_pass',
            field=models.TextField(null=True),
        ),
    ]
