# Generated by Django 5.2.1 on 2025-09-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froxa', '0004_userfroxa_action_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(null=True)),
                ('message', models.TimeField(null=True)),
                ('time_log', models.TextField(null=True)),
                ('url_file', models.TextField(null=True)),
            ],
        ),
    ]
