# Generated by Django 5.2.1 on 2025-09-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froxa', '0005_notify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='url_file',
            new_name='file',
        ),
        migrations.AddField(
            model_name='notify',
            name='sent',
            field=models.TextField(null=True),
        ),
    ]
