# Generated by Django 5.2.1 on 2025-09-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froxa', '0006_rename_url_file_notify_file_notify_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
