# Generated by Django 5.2.1 on 2025-09-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froxa', '0007_alter_notify_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='art_notice',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notify',
            name='of_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notify',
            name='year',
            field=models.TextField(null=True),
        ),
    ]
